
import type { Metadata, Viewport } from "next";
import { Inter, Playfair_Display, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";
import SmoothScroll from "@/components/SmoothScroll";
import CustomCursor from "@/components/CustomCursor";

import ScrollProgress from "@/components/ScrollProgress";
import Analytics from "@/components/Analytics";
import { portfolioData, SITE_URL } from "@/data/portfolio";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
});

const TITLE = "Yash Srivastava | Full Stack Developer & DevSecOps Enthusiast";
const DESCRIPTION =
  "Final-year B.Tech Computer Science student building systems end-to-end. Hands-on with CI/CD, Docker, Kubernetes, cloud-native workflows and LLM-powered apps. Open to SDE, DevOps, and Cloud roles.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  keywords: ["Yash Srivastava", "Full Stack Developer", "DevSecOps", "DevOps", "Software Engineer", "React", "Next.js", "Docker", "Kubernetes", "CI/CD", "Cloud", "LangGraph", "Portfolio"],
  authors: [{ name: "Yash Srivastava", url: "https://github.com/yashsrivastava1408" }],
  creator: "Yash Srivastava",
  alternates: { canonical: "/" },
  // The share image, favicon and app icons are generated by opengraph-image.tsx, icon.tsx and apple-icon.tsx.
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "/",
    siteName: "Yash Srivastava Portfolio",
    title: TITLE,
    description: "Build scalable systems. Deploy with confidence. Final-year CSE student with hands-on DevOps experience.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Yash Srivastava | Portfolio",
    description: "Full Stack Developer & DevSecOps Enthusiast. Building scalable systems end-to-end.",
  },
  robots: {
    index: true,
    follow: true,
  },
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#05060e",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Person",
        "@id": `${SITE_URL}/#person`,
        name: portfolioData.personal.name,
        jobTitle: "Full Stack Developer & DevSecOps Enthusiast",
        url: SITE_URL,
        email: portfolioData.personal.email,
        telephone: portfolioData.personal.phone,
        sameAs: portfolioData.personal.social.map(s => s.url),
        alumniOf: {
          "@type": "CollegeOrUniversity",
          name: portfolioData.education[0].institution,
        },
        knowsAbout: portfolioData.skills,
        description: portfolioData.personal.description,
        image: `${SITE_URL}/profile-hero.jpg`,
      },
      {
        "@type": "WebSite",
        "@id": `${SITE_URL}/#website`,
        url: SITE_URL,
        name: "Yash Srivastava | Portfolio",
        description: DESCRIPTION,
        publisher: {
          "@id": `${SITE_URL}/#person`,
        },
      },
      {
        "@type": "ProfilePage",
        "@id": `${SITE_URL}/#webpage`,
        url: SITE_URL,
        isPartOf: {
          "@id": `${SITE_URL}/#website`,
        },
        about: {
          "@id": `${SITE_URL}/#person`,
        },
      },
    ],
  };

  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={clsx(
          inter.variable,
          playfair.variable,
          cormorant.variable,
          "antialiased bg-background text-foreground"
        )}
      >
        <CustomCursor />
        <ScrollProgress />
        <SmoothScroll>{children}</SmoothScroll>
        <Analytics />
      </body>
    </html>
  );
}

